# -*- coding: utf-8 -*-
"""22 more teams manually verified from images: the 18 with anomalously high
(>14) OCR row counts (column-bleed noise) and 4 with anomalously low (<11)
counts from the pass-1 extraction."""
import csv, difflib, os

SCRATCH = r"C:\Users\BenTa\AppData\Local\Temp\claude\C--Users-BenTa-OneDrive-Desktop-College-Football\219ab1a4-16a9-41b1-bed9-02f025818d0f\scratchpad"
OUT_CSV = os.path.join(SCRATCH, "athlon_2026_schedules_manual_batch2.csv")

FBS_TEAMS = sorted(set([
    "Boston College", "Cal", "Clemson", "Duke", "Florida State", "Georgia Tech",
    "Louisville", "Miami (Fla.)", "North Carolina", "NC State", "Pitt", "SMU",
    "Stanford", "Syracuse", "Virginia", "Virginia Tech", "Wake Forest",
    "Army", "Charlotte", "East Carolina", "Florida Atlantic", "Memphis", "Navy",
    "North Texas", "Rice", "South Florida", "Temple", "Tulane", "Tulsa", "UAB", "UTSA",
    "Arizona", "Arizona State", "Baylor", "BYU", "Cincinnati", "Colorado", "Houston",
    "Iowa State", "Kansas", "Kansas State", "Oklahoma State", "TCU", "Texas Tech",
    "UCF", "Utah", "West Virginia",
    "Illinois", "Indiana", "Iowa", "Maryland", "Michigan", "Michigan State",
    "Minnesota", "Nebraska", "Northwestern", "Ohio State", "Oregon", "Penn State",
    "Purdue", "Rutgers", "UCLA", "USC", "Washington", "Wisconsin",
    "Delaware", "FIU", "Jacksonville State", "Kennesaw State", "Liberty",
    "Middle Tennessee", "Missouri State", "New Mexico State", "Sam Houston", "WKU",
    "Notre Dame", "UConn",
    "Akron", "Ball State", "Bowling Green", "Buffalo", "Central Michigan",
    "Eastern Michigan", "Kent State", "Miami (Ohio)", "Ohio", "Sacramento State",
    "Toledo", "UMass", "Western Michigan",
    "Air Force", "Hawai'i", "Nevada", "New Mexico", "North Dakota State",
    "Northern Illinois", "San Jose State", "UNLV", "UTEP", "Wyoming",
    "Boise State", "Colorado State", "Fresno State", "Oregon State", "San Diego State",
    "Texas State", "Utah State", "Washington State",
    "Alabama", "Arkansas", "Auburn", "Florida", "Georgia", "Kentucky", "LSU",
    "Mississippi State", "Missouri", "Oklahoma", "Ole Miss", "South Carolina",
    "Tennessee", "Texas", "Texas A&M", "Vanderbilt",
    "Appalachian State", "Coastal Carolina", "Georgia Southern", "Georgia State",
    "James Madison", "Marshall", "Old Dominion", "Arkansas State", "Louisiana",
    "Louisiana Tech", "South Alabama", "Southern Miss", "Troy", "ULM",
]))

SCHEDULES = {
    "Florida State": [
        ("Aug. 29", "New Mexico State", "home"),
        ("Sept. 7", "SMU", "home"),
        ("Sept. 19", "at Alabama", "away"),
        ("Sept. 26", "Central Arkansas", "home"),
        ("Oct. 3", "Virginia", "home"),
        ("Oct. 9", "at Louisville", "away"),
        ("Oct. 17", "at Miami (Fla.)", "away"),
        ("Oct. 31", "Clemson", "home"),
        ("Nov. 7", "at Boston College", "away"),
        ("Nov. 13", "at Pitt", "away"),
        ("Nov. 21", "NC State", "home"),
        ("Nov. 27", "Florida", "home"),
    ],
    "Georgia Tech": [
        ("Sept. 3", "Colorado", "home"),
        ("Sept. 12", "Tennessee", "home"),
        ("Sept. 19", "Mercer", "home"),
        ("Sept. 26", "at Stanford", "away"),
        ("Oct. 10", "Duke", "home"),
        ("Oct. 17", "at Virginia Tech", "away"),
        ("Oct. 24", "Boston College", "home"),
        ("Oct. 31", "at Pitt", "away"),
        ("Nov. 7", "Louisville", "home"),
        ("Nov. 14", "at Clemson", "away"),
        ("Nov. 21", "Wake Forest", "home"),
        ("Nov. 28", "at Georgia", "away"),
    ],
    "Illinois": [
        ("Sept. 5", "UAB", "home"),
        ("Sept. 12", "Duke", "home"),
        ("Sept. 19", "Southern Illinois", "home"),
        ("Sept. 26", "at Ohio State", "away"),
        ("Oct. 3", "Purdue", "home"),
        ("Oct. 10", "at Michigan State", "away"),
        ("Oct. 24", "Oregon", "home"),
        ("Oct. 31", "at Maryland", "away"),
        ("Nov. 7", "Nebraska", "home"),
        ("Nov. 14", "at UCLA", "away"),
        ("Nov. 21", "Iowa", "home"),
        ("Nov. 28", "at Northwestern", "away"),
    ],
    "Texas Tech": [
        ("Sept. 5", "Abilene Christian", "home"),
        ("Sept. 12", "at Oregon State", "away"),
        ("Sept. 19", "Houston", "home"),
        ("Sept. 26", "Sam Houston", "home"),
        ("Oct. 3", "at Colorado", "away"),
        ("Oct. 17", "Arizona State", "home"),
        ("Oct. 24", "at Cincinnati", "away"),
        ("Oct. 31", "Arizona", "home"),
        ("Nov. 7", "West Virginia", "home"),
        ("Nov. 14", "at Oklahoma State", "away"),
        ("Nov. 21", "at Baylor", "away"),
        ("Nov. 28", "TCU", "home"),
    ],
    "Washington": [
        ("Sept. 5", "Washington State", "home"),
        ("Sept. 12", "Utah State", "home"),
        ("Sept. 19", "E. Washington", "home"),
        ("Sept. 26", "Minnesota", "home"),
        ("Oct. 3", "at USC", "away"),
        ("Oct. 10", "Iowa", "home"),
        ("Oct. 17", "at Purdue", "away"),
        ("Oct. 31", "at Nebraska", "away"),
        ("Nov. 7", "Penn State", "home"),
        ("Nov. 14", "at Michigan State", "away"),
        ("Nov. 21", "Indiana", "home"),
        ("Nov. 28", "at Oregon", "away"),
    ],
    "Wisconsin": [
        ("Sept. 6", "vs. Notre Dame #", "neutral"),
        ("Sept. 12", "Western Illinois", "home"),
        ("Sept. 19", "Eastern Michigan", "home"),
        ("Sept. 26", "at Penn State", "away"),
        ("Oct. 3", "Michigan State", "home"),
        ("Oct. 17", "at UCLA", "away"),
        ("Oct. 24", "USC", "home"),
        ("Oct. 31", "at Iowa", "away"),
        ("Nov. 7", "Rutgers", "home"),
        ("Nov. 14", "at Maryland", "away"),
        ("Nov. 21", "at Purdue", "away"),
        ("Nov. 28", "Minnesota", "home"),
    ],
    "WKU": [
        ("Sept. 5", "at Nevada", "away"),
        ("Sept. 12", "at Georgia", "away"),
        ("Sept. 19", "Indiana", "home"),
        ("Sept. 26", "Mercyhurst", "home"),
        ("Oct. 1", "at New Mexico State", "away"),
        ("Oct. 8", "Missouri State", "home"),
        ("Oct. 14", "at Sam Houston", "away"),
        ("Oct. 27", "Delaware", "home"),
        ("Nov. 7", "at Middle Tennessee", "away"),
        ("Nov. 14", "Jacksonville State", "home"),
        ("Nov. 21", "at Liberty", "away"),
        ("Nov. 28", "Kennesaw State", "home"),
    ],
    "Akron": [
        ("Sept. 3", "at Wake Forest", "away"),
        ("Sept. 12", "Robert Morris", "home"),
        ("Sept. 19", "at Minnesota", "away"),
        ("Sept. 26", "UNLV", "home"),
        ("Oct. 3", "at Central Michigan", "away"),
        ("Oct. 10", "Eastern Michigan", "home"),
        ("Oct. 17", "at Miami (Ohio)", "away"),
        ("Oct. 24", "at Kent State", "away"),
        ("Nov. 3", "Ohio", "home"),
        ("Nov. 10", "Western Michigan", "home"),
        ("Nov. 18", "at UMass", "away"),
        ("Nov. 27", "Buffalo", "home"),
    ],
    "Ole Miss": [
        ("Sept. 6", "vs. Louisville #", "neutral"),
        ("Sept. 12", "Charlotte", "home"),
        ("Sept. 19", "LSU", "home"),
        ("Sept. 26", "at Florida", "away"),
        ("Oct. 10", "at Vanderbilt", "away"),
        ("Oct. 17", "Missouri", "home"),
        ("Oct. 24", "at Texas", "away"),
        ("Oct. 31", "Auburn", "home"),
        ("Nov. 7", "Georgia", "home"),
        ("Nov. 14", "at Oklahoma", "away"),
        ("Nov. 21", "Wofford", "home"),
        ("Nov. 28", "Mississippi State", "home"),
    ],
    "South Carolina": [
        ("Sept. 5", "Kent State", "home"),
        ("Sept. 12", "Towson", "home"),
        ("Sept. 19", "Mississippi State", "home"),
        ("Sept. 26", "at Alabama", "away"),
        ("Oct. 3", "Kentucky", "home"),
        ("Oct. 10", "at Florida", "away"),
        ("Oct. 24", "Tennessee", "home"),
        ("Oct. 31", "at Oklahoma", "away"),
        ("Nov. 7", "Texas A&M", "home"),
        ("Nov. 14", "at Arkansas", "away"),
        ("Nov. 21", "Georgia", "home"),
        ("Nov. 28", "at Clemson", "away"),
    ],
    "Arkansas": [
        ("Sept. 5", "North Alabama", "home"),
        ("Sept. 12", "at Utah", "away"),
        ("Sept. 19", "Georgia", "home"),
        ("Sept. 26", "Tulsa", "home"),
        ("Oct. 3", "at Texas A&M", "away"),
        ("Oct. 10", "Tennessee", "home"),
        ("Oct. 17", "at Vanderbilt", "away"),
        ("Oct. 31", "Missouri", "home"),
        ("Nov. 7", "at Auburn", "away"),
        ("Nov. 14", "South Carolina", "home"),
        ("Nov. 21", "at Texas", "away"),
        ("Nov. 28", "LSU", "home"),
    ],
    "Army": [
        ("Sept. 5", "Bryant", "home"),
        ("Sept. 12", "South Florida", "home"),
        ("Sept. 26", "at Temple", "away"),
        ("Oct. 3", "at Louisiana Tech", "away"),
        ("Oct. 10", "Tulane", "home"),
        ("Oct. 17", "Florida Atlantic", "home"),
        ("Oct. 23", "at Tulsa", "away"),
        ("Oct. 31", "at Memphis", "away"),
        ("Nov. 7", "Air Force", "home"),
        ("Nov. 21", "East Carolina", "home"),
        ("Nov. 28", "at Rice", "away"),
        ("Dec. 12", "vs. Navy #", "neutral"),
    ],
    "Central Michigan": [
        ("Sept. 5", "at New Mexico", "away"),
        ("Sept. 12", "Colgate", "home"),
        ("Sept. 19", "Wyoming", "home"),
        ("Sept. 26", "at Miami (Fla.)", "away"),
        ("Oct. 3", "Akron", "home"),
        ("Oct. 10", "at Ohio", "away"),
        ("Oct. 17", "Western Michigan", "home"),
        ("Oct. 24", "Miami (Ohio)", "home"),
        ("Nov. 4", "Eastern Michigan #", "home"),
        ("Nov. 11", "Sacramento State", "home"),
        ("Nov. 18", "at Buffalo", "away"),
        ("Nov. 28", "at Ball State", "away"),
    ],
    "Georgia State": [
        ("Sept. 5", "North Carolina A&T", "home"),
        ("Sept. 12", "at Kennesaw State", "away"),
        ("Sept. 19", "at UCF", "away"),
        ("Sept. 26", "Northern Illinois", "home"),
        ("Oct. 3", "Old Dominion", "home"),
        ("Oct. 17", "at James Madison", "away"),
        ("Oct. 24", "at Arkansas State", "away"),
        ("Oct. 31", "Coastal Carolina", "home"),
        ("Nov. 7", "at Appalachian State", "away"),
        ("Nov. 14", "Georgia Southern", "home"),
        ("Nov. 21", "at Marshall", "away"),
        ("Nov. 28", "Louisiana", "home"),
    ],
    "Navy": [
        ("Sept. 5", "Towson", "home"),
        ("Sept. 12", "at Florida Atlantic", "away"),
        ("Sept. 25", "at UAB", "away"),
        ("Oct. 3", "at Air Force", "away"),
        ("Oct. 10", "Tulsa", "home"),
        ("Oct. 17", "at UTSA", "away"),
        ("Oct. 24", "North Texas", "home"),
        ("Oct. 31", "vs. Notre Dame #", "neutral"),
        ("Nov. 7", "Temple", "home"),
        ("Nov. 21", "Memphis", "home"),
        ("Nov. 28", "at Charlotte", "away"),
        ("Dec. 12", "vs. Army %", "neutral"),
    ],
    "Notre Dame": [
        ("Sept. 6", "vs. Wisconsin #", "neutral"),
        ("Sept. 12", "Rice", "home"),
        ("Sept. 19", "Michigan State", "home"),
        ("Sept. 26", "at Purdue", "away"),
        ("Oct. 3", "at North Carolina", "away"),
        ("Oct. 10", "Stanford", "home"),
        ("Oct. 17", "at BYU", "away"),
        ("Oct. 31", "vs. Navy %", "neutral"),
        ("Nov. 7", "Miami (Fla.)", "home"),
        ("Nov. 14", "Boston College", "home"),
        ("Nov. 21", "SMU", "home"),
        ("Nov. 28", "at Syracuse", "away"),
    ],
    "Oklahoma": [
        ("Sept. 5", "UTEP", "home"),
        ("Sept. 12", "at Michigan", "away"),
        ("Sept. 19", "New Mexico", "home"),
        ("Sept. 26", "at Georgia", "away"),
        ("Oct. 10", "vs. Texas #", "neutral"),
        ("Oct. 17", "Kentucky", "home"),
        ("Oct. 24", "at Mississippi State", "away"),
        ("Oct. 31", "South Carolina", "home"),
        ("Nov. 7", "at Florida", "away"),
        ("Nov. 14", "Ole Miss", "home"),
        ("Nov. 21", "Texas A&M", "home"),
        ("Nov. 28", "at Missouri", "away"),
    ],
    "TCU": [
        ("Aug. 29", "vs. North Carolina #", "neutral"),
        ("Sept. 12", "Grambling State", "home"),
        ("Sept. 19", "Arkansas State", "home"),
        ("Sept. 26", "at UCF", "away"),
        ("Oct. 3", "BYU", "home"),
        ("Oct. 17", "at Baylor", "away"),
        ("Oct. 24", "West Virginia", "home"),
        ("Oct. 31", "Kansas", "home"),
        ("Nov. 7", "at Arizona", "away"),
        ("Nov. 14", "Kansas State", "home"),
        ("Nov. 21", "Utah", "home"),
        ("Nov. 28", "at Texas Tech", "away"),
    ],
    "San Diego State": [
        ("Sept. 5", "Portland State", "home"),
        ("Sept. 12", "at UCLA", "away"),
        ("Sept. 19", "James Madison", "home"),
        ("Sept. 26", "at Toledo", "away"),
        ("Oct. 3", "Texas State", "home"),
        ("Oct. 10", "at Oregon State", "away"),
        ("Oct. 17", "Fresno State", "home"),
        ("Oct. 24", "at Colorado State", "away"),
        ("Oct. 31", "Washington State", "home"),
        ("Nov. 14", "Utah State", "home"),
        ("Nov. 21", "at Boise State", "away"),
        ("Nov. 28", "at Fresno State #", "away"),
    ],
    "South Florida": [
        ("Sept. 5", "FIU", "home"),
        ("Sept. 12", "at Army", "away"),
        ("Sept. 19", "Delaware State", "home"),
        ("Sept. 26", "at Bowling Green", "away"),
        ("Oct. 3", "Temple", "home"),
        ("Oct. 8", "at UTSA", "away"),
        ("Oct. 17", "Kent State", "home"),
        ("Oct. 31", "UAB", "home"),
        ("Nov. 6", "at East Carolina", "away"),
        ("Nov. 12", "Memphis", "home"),
        ("Nov. 21", "at Florida Atlantic", "away"),
        ("Nov. 27", "Tulane", "home"),
    ],
    "Texas A&M": [
        ("Sept. 5", "Missouri State", "home"),
        ("Sept. 12", "Arizona State", "home"),
        ("Sept. 19", "Kentucky", "home"),
        ("Sept. 26", "at LSU", "away"),
        ("Oct. 3", "Arkansas", "home"),
        ("Oct. 10", "at Missouri", "away"),
        ("Oct. 17", "The Citadel", "home"),
        ("Oct. 24", "at Alabama", "away"),
        ("Nov. 7", "at South Carolina", "away"),
        ("Nov. 14", "Tennessee", "home"),
        ("Nov. 21", "at Oklahoma", "away"),
        ("Nov. 27", "Texas", "home"),
    ],
    "Washington State": [
        ("Sept. 5", "at Washington", "away"),
        ("Sept. 12", "at Kansas State", "away"),
        ("Sept. 19", "Duquesne", "home"),
        ("Sept. 26", "Arizona", "home"),
        ("Oct. 3", "Fresno State", "home"),
        ("Oct. 10", "at Utah State", "away"),
        ("Oct. 17", "at Oregon State", "away"),
        ("Oct. 24", "Boise State", "home"),
        ("Oct. 31", "at San Diego State", "away"),
        ("Nov. 14", "Colorado State", "home"),
        ("Nov. 21", "at Texas State", "away"),
        ("Nov. 28", "Oregon State #", "home"),
    ],
}

def match_opponent(raw):
    cleaned = raw.replace("at ", "").replace("vs. ", "").replace("#", "").replace("%", "").strip()
    matches = difflib.get_close_matches(cleaned, FBS_TEAMS, n=1, cutoff=0.55)
    if matches:
        conf = round(difflib.SequenceMatcher(None, cleaned.lower(), matches[0].lower()).ratio(), 2)
        if conf >= 0.75:
            return matches[0]
    return ""

def main():
    fieldnames = ["team", "game_number", "date_raw", "opponent_raw", "opponent_matched", "home_away", "match_confidence"]
    with open(OUT_CSV, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for team, games in SCHEDULES.items():
            for i, (date_raw, opp_raw, ha) in enumerate(games, 1):
                matched = match_opponent(opp_raw)
                conf = 1.0 if matched else ""
                w.writerow({
                    "team": team, "game_number": i, "date_raw": date_raw,
                    "opponent_raw": opp_raw, "opponent_matched": matched,
                    "home_away": ha, "match_confidence": conf,
                })
    total = sum(len(v) for v in SCHEDULES.values())
    print(f"Wrote {total} manually-verified rows for {len(SCHEDULES)} teams to {OUT_CSV}")

if __name__ == "__main__":
    main()
